# Site settings
title: Bryan's blog
header-img: img/home-bg.png
email: bryan.hou94@gmail.com
copyright_name: bryanhou1
description: > # this means to ignore newlines until "baseurl:"
  learn with bryan
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bryanhou1
learn_profile: bryanhou1
email_username: bryan.hou94@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
